#!/usr/bin/ruby

### Manage public provider credentials easily into Abiquo platform enterprises
## The usege is so easy too, only requires a yaml configuration file with the provider credentials to use.
## File: $HOME/cloud_credentials.yml
## Example:
#   Api:
#       location: http://host:80/api
#       user: user
#       password: pass
#
#   AMAZON:
#       id:  amazon_accesskey
#       key: amazon_key
#   digitalocean:
#       id:  do_api_id
#       key: do_key

require 'json'
require 'net/https'
require 'yaml'
require 'thor'
require 'colorize'

class Conf
    def initialize
        @conf = YAML.load_file("#{ENV["HOME"]}/cloud_credentials.yml")
    end

    def conf
        @conf
    end

    def location
        @conf['Api']['location']
    end

    def user
        @conf['Api']['user']
    end

    def password
        @conf['Api']['password']
    end
end

class ManageCredentials < Thor

    desc "add <provider> <enterprise>", "Adds the credentials for <provider> into the <enterprise>"
    def add(provider, enterprise)
        BusinessService.new(Conf.new).add(provider, enterprise)
    end

    option :remote, :type => :boolean
    desc "list_providers [remote]", "Lists the config file providers. --remote option will list the remote ones"
    def list_providers
        BusinessService.new(Conf.new).list_providers(options.remote)
    end

    desc "release <provider> <enterprise>", "Release the credentials for <provider> from the <enterprise>"
    def release(provider, enterprise)
        BusinessService.new(Conf.new).release(provider, enterprise)
    end

    desc "list <enterprise>", "List the attached credientials of the <enterprise>"
    def list(enterprise)
        BusinessService.new(Conf.new).list(enterprise)
    end

    desc "printkeys <provider>", "Print the provider keys"
    def printkeys(provider)
        BusinessService.new(Conf.new).print(provider)
    end
end

class BusinessService
    def initialize(conf)
        @conf = conf
        @client = ApiClient.new(conf)
    end

    def add(provider, enterprise)
        raise Exception.new("Provider #{provider} not found in configuration file") if @conf.conf[provider].nil?

        key = @conf.conf[provider]['key']
        access = @conf.conf[provider]['id']
        link = @client.get_technology_link(provider)

        raise Exception.new("No link found for provider: #{provider}".colorize(:red)) if link.nil?
        puts "#{@client.post_credentials(key, access, enterprise, link)}".colorize(:green)
    end

    def list_providers(remote)
        puts "#{@client.get_providers(remote)}".colorize(:green)
    end

    def release(provider, enterprise)
        puts "#{@client.delete_credentials(provider, enterprise)}".colorize(:green)
    end

    def list(enterprise)
        puts "#{@client.list_credentials(enterprise)}".colorize(:green)
    end
    
    def print(provider)
        if provider != nil
            puts @conf.conf[provider]["id"]
            puts "id", "#{@conf.conf[provider]["id"]}".colorize(:cyan)
            puts "key", "#{@conf.conf[provider]["key"]}".colorize(:cyan)
        end
    end
end

class ApiClient
    def initialize(conf)
        @conf = conf
    end

    # Given an enterprise name returns the enterprise id
    # Parans:
    #   +enterprise_name+:: The name of the enterprise where get the id
    def get_enterprise_id(enterprise_name)
        request = Net::HTTP::Get.new("#{@conf.location}/admin/enterprises")
        request.add_field('accept', 'application/vnd.abiquo.enterprises+json')
        puts "Searching for enterprise #{enterprise_name}..."
        response = send_request(request)
        ids = JSON.parse(response.body)["collection"].select{ |x| x["name"] == enterprise_name }.collect{ |x| x["id"] }
        enterprise_id = if ids.empty? then nil else ids[0] end
        raise Exception.new("Enterprise #{enterprise_name} not found".colorize(:red)) if enterprise_id.nil?
        enterprise_id
    end
    
    # Retrieves the technology (rel=hypervisor) link from the api
    # Params:
    #   +provider+:: the provisor (hypervisor) link to retrieve
    def get_technology_link(provider)
        request = Net::HTTP::Get.new("#{@conf.location}/config/hypervisortypes")
        request.add_field('accept','application/vnd.abiquo.hypervisortypes+json')
        puts "Searching for provider #{provider}..."
        response = send_request(request)
        provider_type = JSON.parse(response.body)["collection"].select{ |x| x["name"] == provider }[0]
        link = provider_type["links"].select{ |link| link["rel"] == "self" }[0]
        link['rel'] = 'hypervisortype'
        link
    end

    # Sets the creadentials to the enterprise
    # Params:
    #   +key+:: credentials key
    #   +access+:: credentials access
    #   +enterprise+:: enterprise where set the credentials
    #   +link+:: the provider link where the credentials belong
    def post_credentials(key, access, enterprise, link)
        ent_id = get_enterprise_id(enterprise)
        request = Net::HTTP::Post.new("#{@conf.location}/admin/enterprises/#{ent_id}/credentials")
        request.add_field('content-type', 'application/vnd.abiquo.publiccloudcredentials+json')
        request.add_field('accept', 'application/vnd.abiquo.publiccloudcredentials+json')
        request.body = "{ \"links\": [#{link.to_json}], "
        request.body << "\"key\": \"#{key}\", \"access\": \"#{access}\"}"
        puts "Posting credentials into enterprise #{enterprise}..."
        send_request(request).body
    end

    # Retrieves the credentials of an enterprise
    # Params:
    #   +enterprise+:: where retireve the credentials
    def get_credentials(enterprise)
        ent_id = get_enterprise_id(enterprise)
        request = Net::HTTP::Get.new("#{@conf.location}/admin/enterprises/#{ent_id}/credentials")
        request.add_field('accept', 'application/vnd.abiquo.publiccloudcredentialslist+json')
        puts "Retrieving credentials for enterprise #{enterprise}..."
        send_request(request).body
    end

    # Remove the credentials of a provider from an enterprise
    # Params:
    #   +provider+:: provider of the credentials to remove
    #   +ent_id+:: identifier of the enterprise which remove the credentials
    def delete_credentials(provider, enterprise)
        credentials = get_credentials(enterprise)
        coll = JSON.parse(credentials)["collection"]
        links = coll.collect{ |x| x["links"] }
        creds = links[0].select{ |link| link["rel"] == "edit" }[0]
        raise Exception.new("No credentials found for enterprise #{enterprise} and provider #{provider}".colorize(:red)) if creds.empty?
        puts "Deleting the credentials of the provider #{provider} from the enterprise #{enterprise}"
        send_request(Net::HTTP::Delete.new(creds["href"])).body
    end

    # Returns the provider names of the credentials attached to the given enterprise
    # Params:
    #   +enterprise+:: where get the credentials
    def list_credentials(enterprise)
        links = JSON.parse(get_credentials(enterprise))["collection"].collect{ |cred| cred["links"] }.zip
        match = links[0][0].select{ |link| link["rel"] == "hypervisortype" }
        match.collect{ |link| link["title"] }
    end


    # Send the request
    # Params:
    #   +request+:: the request to send
    def send_request(request)
        uri = URI.parse(@conf.location)
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE
        request.basic_auth(@conf.user, @conf.password)
        response = http.request(request)
        puts "#{response.code} - #{response.message}"
        if not response.code =~ /2\d\d/
            if not response.body.nil? and not response.body.empty?
                json = JSON.parse(response.body)
                puts json
                codes = json["collection"].collect{ |x| x["code"] }
                messages = json["collection"].collect{ |x| x["messages"] }
                ex_message = ""
                codes.zip(messages).each do |code, message|
                    ex_message << "#{code} - #{message}\n"
                end
            else
                ex_message=""
            end
            raise Exception.new(ex_message.colorize(:red))
        end
        response
    end

    # Retrieves the list of all providers available to use.
    # Params:
    #   +remote+:: if <true> performs an api call and return all api configured providers,
    #              else returns all providers from config file.
    def get_providers(remote)
        if remote
            request = Net::HTTP::Get.new("#{@conf.location}/config/hypervisortypes")
            request.add_field('accept','application/vnd.abiquo.hypervisortypes+json')
            puts "Getting configured provider from api #{@conf.location}..."
            response = send_request(request)
            providers = JSON.parse(response.body)["collection"].collect{ |prov| "#{prov["name"]} #{prov["realName"]}" }
        else
            providers = @conf.conf.keys
            providers.delete('Api')
        end
        providers.sort
    end

end

# exectute it
ManageCredentials.start(ARGV)
